### ISSUE TITLE
Meilisearch with Pydantic v2

### ISSUE THREAD

**Issue by sanders41** [prrao87/async-db-fastapi#31]
I saw you updated Neo4j to use Pydantic 2, `meilisearch-python-async` has also been updated with support for Pydantic 2. I have been meaning to try that out and see what difference it makes here, but just haven't gotten to it yet.

**Comment by prrao87** [comment]
Awesome! Yes, I in fact had some local commits that I haven't pushed yet to run it for the Meilisearch case next... Other than the initial data validation step, are there other areas where the async Meilisearch client is affected by pydantic v2's release?

I'll push my changes later today and maybe you can take a look to see if there's something more to be gained?

**Comment by sanders41** [comment]
The latest update just added support for Pydantic v2, there should be no user facing changes. I'm happy to take a look when you push it if you want.
